- hosts: gpus
  become: true
  become_user: root
  roles:
    - { role: base }
    - { role: docker-ce, docker_version: 17.12.1 }
    - { role: cuda, cuda_version_major: 9, cuda_version_minor: 1 }
    - { role: cudnn, cuda_version_major: 9, cuda_version_minor: 1, cudnn_version: 7 }
    - { role: nvidia-docker, nvidia_docker_version: 2.0.3 }
