---
# Include variables and define needed variables.
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - always

# Pre tasks
- include_tasks: "pre-{{ ansible_distribution }}.yml"
  tags:
    - always

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_distribution }}.yml"
  tags:
    - install

# Configure Docker.
- include_tasks: "configure-Ubuntu.yml"
  tags:
    - install
    - configure

- name: Ensure Docker has selected state and enabled on boot.
  service:
    name: "{{ docker_service }}"
    state: "{{ docker_state }}"
    enabled: yes
  tags:
    - always
